/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./static/**/*.{html,js,css}", "./templates/**/*.{html,js,css}", "./node_modules/flowbite/**/*.js"],
  mode: "jit",
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: {
          50: "#f8fafc",
          100: "#f1f5f9",
          200: "#e2e8f0",
          300: "#cbd5e1",
          400: "#94a3b8",
          500: "#64748b",
          600: "#475569",
          700: "#334155",
          800: "#1e293b",
          900: "#0f172a",
          950: "#020617",
        },
      },
      width: {
        1440: "1440px",
        1240: "1240px",
        321: "321px",
        545: "545px",
        390: "390px",
        259: "259px",
        610: "610px",
        139: "139px",
        240: "240px",
        420: "420px",
        166: "166px",
        125: "125px",
        350: "350px",
        100: "100px",
        150: "150px",
      },
      height: {
        530: "530px",
        937: "937px",
        242: "242px",
      },
      margin: {
        400: "400px",
      },
      backgroundColor: {
        "input-color": "#F0F0F0",
      },
      fontFamily: {
        body: [
          "Nunito",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "system-ui",
          "Segoe UI",
          "Roboto",
          "Helvetica Neue",
          "Arial",
          "Noto Sans",
          "sans-serif",
          "Apple Color Emoji",
          "Segoe UI Emoji",
          "Segoe UI Symbol",
          "Noto Color Emoji",
        ],
      },
    },
  },
  plugins: [require("@tailwindcss/typography"), require("flowbite/plugin")],
};
